name: Microsoft Teams Notification (Pull-Request)

on:
  pull_request:
    types:
      - opened

jobs:
  send_notification:
    name: Pull-Request Notification
    runs-on: ubuntu-latest
    
    steps:
      - name: Check GitHub Repository
        uses: actions/checkout@v3.5.2

      - name: Send Teams Notification
        uses: mikesprague/teams-incoming-webhook-action@v1
        with:
          github-token: ${{ github.token }}
          webhook-url: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: 'Verzoek om pull-request te reviewen'
          message: |
             ${{ github.actor }} heeft een pull-request aangemaakt (${{ github.event.pull_request.title }})! \
             Klik [hier](${{ github.event.pull_request.html_url }}) om naar de pagina van de pull-request te gaan.